// Package v1 Code generated by swaggo/swag. DO NOT EDIT
package v1

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/algo": {
            "get": {
                "description": "列出所有检测算法",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "algo"
                ],
                "summary": "列出所有检测算法",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.DetectAlgoResult"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "创建检测算法",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "algo"
                ],
                "summary": "创建检测算法",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateDetectAlgoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.DetectAlgoResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/algo/{id}": {
            "get": {
                "description": "获取检测算法",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "algo"
                ],
                "summary": "获取检测算法",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "算法ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.DetectAlgoResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除检测算法",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "algo"
                ],
                "summary": "删除检测算法",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "算法ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/algo/{id}/classes": {
            "put": {
                "description": "更新检测算法类别",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "algo"
                ],
                "summary": "更新检测算法类别",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "算法ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.DetectClassResult"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.DetectAlgoResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/areas": {
            "get": {
                "description": "获取搜索区域的详细信息，包括区域的点列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "area"
                ],
                "summary": "获取搜索区域的详细信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "区域ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "区域名称",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.AreaResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "创建搜索区域",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "area"
                ],
                "summary": "创建搜索区域",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateAreaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.AreaResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/areas/list": {
            "get": {
                "description": "列出所有搜索区域，不返回每个区域的点列表，仅返回中心点位置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "area"
                ],
                "summary": "列出所有搜索区域",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.AreaListResult"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/drone/list": {
            "get": {
                "description": "列出所有绑定的无人机，包含不在线的无人机",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drone"
                ],
                "summary": "列出所有无人机",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.DroneItemResult"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Web/Pilot端统一用户登录，根据是否携带 SN 切换登录方式",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Web/Pilot端统一用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/v1.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.LoginResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.AreaListResult": {
            "type": "object",
            "properties": {
                "center_lat": {
                    "type": "number"
                },
                "center_lng": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "v1.AreaResult": {
            "type": "object",
            "properties": {
                "center_lat": {
                    "type": "number"
                },
                "center_lng": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.PointResult"
                    }
                }
            }
        },
        "v1.CreateAreaRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Request for test."
                },
                "name": {
                    "type": "string",
                    "example": "test"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "index": {
                                "type": "integer"
                            },
                            "lat": {
                                "type": "number"
                            },
                            "lng": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        },
        "v1.CreateDetectAlgoRequest": {
            "type": "object",
            "properties": {
                "algo_path": {
                    "type": "string"
                },
                "algo_version": {
                    "type": "string"
                },
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.DetectClassResult"
                    }
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "v1.DetectAlgoResult": {
            "type": "object",
            "properties": {
                "algo_path": {
                    "type": "string"
                },
                "algo_version": {
                    "type": "string"
                },
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.DetectClassResult"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "v1.DetectClassResult": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "v1.DroneItemResult": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_rtk_available": {
                    "description": "IsRTKAvailable 是否支持RTK",
                    "type": "boolean"
                },
                "is_thermal_available": {
                    "description": "IsThermalAvailable 是否支持热成像",
                    "type": "boolean"
                },
                "last_login_at": {
                    "description": "LastLoginAt 最后登录时间",
                    "type": "string"
                },
                "product_type": {
                    "description": "ProductType 无人机的型号名称",
                    "type": "string"
                },
                "sn": {
                    "description": "以下字段来自实体信息",
                    "type": "string"
                },
                "status": {
                    "description": "以上字段来自实体信息",
                    "type": "string"
                },
                "sub_type": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "v1.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "admin"
                },
                "sn": {
                    "description": "SN 遥控器 SN，仅 Pilot 端登录时需要提供",
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "v1.LoginResult": {
            "type": "object",
            "properties": {
                "params": {
                    "$ref": "#/definitions/v1.ParamsResult"
                },
                "platform": {
                    "$ref": "#/definitions/v1.PlatformResult"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/v1.UserResult"
                }
            }
        },
        "v1.ParamsResult": {
            "type": "object",
            "properties": {
                "mqtt_host": {
                    "type": "string"
                },
                "mqtt_password": {
                    "type": "string"
                },
                "mqtt_username": {
                    "type": "string"
                }
            }
        },
        "v1.PlatformResult": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "workspace": {
                    "type": "string"
                }
            }
        },
        "v1.PointResult": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            }
        },
        "v1.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "v1.UserResult": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "lqhirwdzgkvv.sealoshzh.site",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "DroneSphere API",
	Description:      "DroneSphere API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
