basePath: /api/v1
definitions:
  v1.AreaListResult:
    properties:
      center_lat:
        type: number
      center_lng:
        type: number
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  v1.AreaResult:
    properties:
      center_lat:
        type: number
      center_lng:
        type: number
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      points:
        items:
          $ref: '#/definitions/v1.PointResult'
        type: array
    type: object
  v1.CreateAreaRequest:
    properties:
      description:
        example: Request for test.
        type: string
      name:
        example: test
        type: string
      points:
        items:
          properties:
            index:
              type: integer
            lat:
              type: number
            lng:
              type: number
          type: object
        type: array
    type: object
  v1.CreateDetectAlgoRequest:
    type: object
  v1.CreateWaylineRequest:
    properties:
      drone_sn:
        type: string
      height:
        type: number
      points:
        items:
          $ref: '#/definitions/v1.PointRequest'
        type: array
    required:
    - drone_sn
    - points
    type: object
  v1.DetectAlgoResult:
    properties:
      algo_path:
        type: string
      algo_version:
        type: string
      classes:
        items:
          $ref: '#/definitions/v1.DetectClassResult'
        type: array
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  v1.DetectClassResult:
    properties:
      key:
        type: string
      name:
        type: string
    type: object
  v1.DroneItemResult:
    properties:
      domain:
        type: string
      id:
        type: integer
      is_rtk_available:
        description: IsRTKAvailable 是否支持RTK
        type: boolean
      is_thermal_available:
        description: IsThermalAvailable 是否支持热成像
        type: boolean
      last_login_at:
        description: LastLoginAt 最后登录时间
        type: string
      product_type:
        description: ProductType 无人机的型号名称
        type: string
      sn:
        description: 以下字段来自实体信息
        type: string
      status:
        description: 以上字段来自实体信息
        type: string
      sub_type:
        type: integer
      type:
        type: integer
    type: object
  v1.JobAreaResult:
    properties:
      name:
        type: string
      points:
        items:
          properties:
            lat:
              type: number
            lng:
              type: number
            marker:
              type: string
          type: object
        type: array
    type: object
  v1.JobDrone:
    properties:
      model:
        type: string
      name:
        type: string
      sn:
        type: string
    type: object
  v1.JobItemResult:
    properties:
      area_name:
        type: string
      description:
        type: string
      drones:
        items:
          type: string
        type: array
      id:
        type: integer
      name:
        type: string
      target_classes:
        items:
          type: string
        type: array
    type: object
  v1.LoginRequest:
    properties:
      password:
        example: admin
        type: string
      sn:
        description: SN 遥控器 SN，仅 Pilot 端登录时需要提供
        example: "123456"
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  v1.LoginResult:
    properties:
      params:
        $ref: '#/definitions/v1.ParamsResult'
      platform:
        $ref: '#/definitions/v1.PlatformResult'
      token:
        type: string
      user:
        $ref: '#/definitions/v1.UserResult'
    type: object
  v1.ParamsResult:
    properties:
      mqtt_host:
        type: string
      mqtt_password:
        type: string
      mqtt_username:
        type: string
    type: object
  v1.PlatformResult:
    properties:
      desc:
        type: string
      platform:
        type: string
      workspace:
        type: string
    type: object
  v1.PointRequest:
    properties:
      index:
        type: integer
      lat:
        type: number
      lng:
        type: number
    type: object
  v1.PointResult:
    properties:
      index:
        type: integer
      lat:
        type: number
      lng:
        type: number
    type: object
  v1.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  v1.SubJobResult:
    properties:
      area:
        $ref: '#/definitions/v1.JobAreaResult'
      drone:
        $ref: '#/definitions/v1.JobDrone'
      index:
        type: integer
    type: object
  v1.UserResult:
    properties:
      id:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  v1.WaylineItemResult:
    properties:
      created_at:
        type: string
      drone_model:
        type: string
      drone_sn:
        type: string
      id:
        type: integer
      s3_key:
        type: string
      upload_user:
        type: string
    type: object
host: lqhirwdzgkvv.sealoshzh.site
info:
  contact: {}
  description: DroneSphere API
  license:
    name: Apache 2.0
  title: DroneSphere API
  version: "1.0"
paths:
  /algo:
    get:
      consumes:
      - application/json
      description: 列出所有检测算法
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/v1.DetectAlgoResult'
                  type: array
              type: object
      summary: 列出所有检测算法
      tags:
      - algo
    post:
      consumes:
      - application/json
      description: 创建检测算法
      parameters:
      - description: 请求体
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/v1.CreateDetectAlgoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.DetectAlgoResult'
              type: object
      summary: 创建检测算法
      tags:
      - algo
  /algo/{id}:
    delete:
      consumes:
      - application/json
      description: 删除检测算法
      parameters:
      - description: 算法ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/v1.Response'
      summary: 删除检测算法
      tags:
      - algo
    get:
      consumes:
      - application/json
      description: 获取检测算法
      parameters:
      - description: 算法ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.DetectAlgoResult'
              type: object
      summary: 获取检测算法
      tags:
      - algo
  /algo/{id}/classes:
    put:
      consumes:
      - application/json
      description: 更新检测算法类别
      parameters:
      - description: 算法ID
        in: path
        name: id
        required: true
        type: integer
      - description: 请求体
        in: body
        name: req
        required: true
        schema:
          items:
            $ref: '#/definitions/v1.DetectClassResult'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.DetectAlgoResult'
              type: object
      summary: 更新检测算法类别
      tags:
      - algo
  /areas:
    get:
      consumes:
      - application/json
      description: 获取搜索区域的详细信息，包括区域的点列表
      parameters:
      - description: 区域ID
        in: query
        name: id
        required: true
        type: integer
      - description: 区域名称
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.AreaResult'
              type: object
      summary: 获取搜索区域的详细信息
      tags:
      - area
    post:
      consumes:
      - application/json
      description: 创建搜索区域
      parameters:
      - description: 请求体
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/v1.CreateAreaRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.AreaResult'
              type: object
      summary: 创建搜索区域
      tags:
      - area
  /areas/list:
    get:
      consumes:
      - application/json
      description: 列出所有搜索区域，不返回每个区域的点列表，仅返回中心点位置
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/v1.AreaListResult'
                  type: array
              type: object
      summary: 列出所有搜索区域
      tags:
      - area
  /drone/list:
    get:
      consumes:
      - application/json
      description: 列出所有绑定的无人机，包含不在线的无人机
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/v1.DroneItemResult'
                  type: array
              type: object
      summary: 列出所有无人机
      tags:
      - drone
  /job:
    get:
      consumes:
      - application/json
      description: 获取所有任务
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/v1.JobItemResult'
                  type: array
              type: object
      summary: 获取所有任务
      tags:
      - job
  /job/{id}:
    get:
      consumes:
      - application/json
      description: 获取任务详细信息
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/v1.SubJobResult'
                  type: array
              type: object
      summary: 获取任务详细信息
      tags:
      - job
  /user/login:
    post:
      consumes:
      - application/json
      description: Web/Pilot端统一用户登录，根据是否携带 SN 切换登录方式
      parameters:
      - description: 登录参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  $ref: '#/definitions/v1.LoginResult'
              type: object
      summary: Web/Pilot端统一用户登录
      tags:
      - user
  /wayline:
    get:
      consumes:
      - application/json
      description: 列出所有航线
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/v1.WaylineItemResult'
                  type: array
              type: object
      summary: 列出所有航线
      tags:
      - wayline
    post:
      consumes:
      - application/json
      description: 根据给出的点序列和无人机SN、高度生成航线
      parameters:
      - description: 请求体
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/v1.CreateWaylineRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 创建航线
      tags:
      - wayline
  /wayline/download:
    get:
      consumes:
      - application/json
      description: 根据给出的key下载航线文件
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 下载航线文件
      tags:
      - wayline
swagger: "2.0"
