basePath: /
definitions:
  dji.DeviceModelRsp:
    properties:
      domain:
        type: string
      key:
        type: string
      sub_type:
        type: string
      type:
        type: string
    type: object
  dji.DeviceTopoRsp:
    properties:
      hosts:
        description: Hosts 飞机设备拓扑集合
        items:
          $ref: '#/definitions/dji.TopoHostDeviceRsp'
        type: array
      parents:
        description: Gateways 网关设备拓扑集合，json key 为 parents
        items:
          $ref: '#/definitions/dji.TopoGatewayDeviceRsp'
        type: array
    type: object
  dji.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  dji.TopoGatewayDeviceRsp:
    properties:
      device_callsign:
        type: string
      device_model:
        $ref: '#/definitions/dji.DeviceModelRsp'
      icon_urls:
        properties:
          normal_icon_url:
            type: string
          selected_icon_url:
            type: string
        type: object
      online_status:
        type: boolean
      sn:
        type: string
      user_callsign:
        type: string
      user_id:
        type: string
    type: object
  dji.TopoHostDeviceRsp:
    properties:
      device_callsign:
        type: string
      device_model:
        $ref: '#/definitions/dji.DeviceModelRsp'
      icon_urls:
        properties:
          normal_icon_url:
            type: string
          selected_icon_url:
            type: string
        type: object
      online_status:
        type: boolean
      sn:
        type: string
      user_callsign:
        type: string
      user_id:
        type: string
    type: object
host: example
info:
  contact: {}
  description: 上云API需要的API模块接口
  license:
    name: Apache 2.0
  title: 上云API模块API
  version: "1.0"
paths:
  /manage/api/v1/workspaces/{workspace_id}/devices/topologies:
    get:
      consumes:
      - application/json
      description: |-
        PILOT在首次上线后，会发送http请求去获取同一个工作空间下的所有设备列表及其拓扑，
        服务端需要把整个设备列表发给PILOT。
        同时，当接收到websocket指令通知设备online/offline/update的时候，
        也是需要调用该接口进行请求设备拓扑列表进行更新。
      parameters:
      - description: 工作空间ID
        in: path
        name: workspace_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/dji.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dji.DeviceTopoRsp'
                  type: array
              type: object
      summary: 获取设备拓扑列表
      tags:
      - dji
swagger: "2.0"
