basePath: /api/v1
definitions:
  v1.LoginRequest:
    properties:
      password:
        example: admin
        type: string
      sn:
        description: SN 遥控器 SN，仅 Pilot 端登录时需要提供
        example: "123456"
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  v1.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
host: localhost:10086
info:
  contact: {}
  description: DroneSphere API
  license:
    name: Apache 2.0
  title: DroneSphere API
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: User login
      parameters:
      - description: 登录参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: login
      tags:
      - user
swagger: "2.0"
