basePath: /api/v1
definitions:
  entity.Drone:
    properties:
      domain:
        type: string
      sn:
        type: string
      status:
        type: integer
      sub_type:
        type: integer
      type:
        type: integer
    type: object
  v1.LoginRequest:
    properties:
      password:
        example: admin
        type: string
      sn:
        description: SN 遥控器 SN，仅 Pilot 端登录时需要提供
        example: "123456"
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  v1.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
host: localhost:10086
info:
  contact: {}
  description: DroneSphere API
  license:
    name: Apache 2.0
  title: DroneSphere API
  version: "1.0"
paths:
  /drone/list:
    get:
      consumes:
      - application/json
      description: 列出所有绑定的无人机，包含不在线的无人机
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.Drone'
                  type: array
              type: object
      summary: 列出所有无人机
      tags:
      - drone
  /user/login:
    post:
      consumes:
      - application/json
      description: Web/Pilot端统一用户登录，根据是否携带 SN 切换登录方式
      parameters:
      - description: 登录参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/v1.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Web/Pilot端统一用户登录
      tags:
      - user
swagger: "2.0"
