name: Docker Build and Push

on:
  push:
    branches:
      - master  # Listen to push events on the master branch
    tags:
      - 'v*'  # Listen to tag events starting with 'v'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: Build and push Docker image (for push to branch)
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository.toLowerCase() }}:${{ steps.meta.outputs.version }}
            ghcr.io/${{ github.repository.toLowerCase() }}:latest

      - name: Extract tag without 'v' prefix
        if: startsWith(github.ref, 'refs/tags/v')
        id: extract_tag
        uses: actions/github-script@v6
        with:
          script: |
            const tag = github.ref.replace('refs/tags/v', '');
            core.setOutput('tag', tag);

      - name: Build and push Docker image (for tag push)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository.toLowerCase() }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository.toLowerCase() }}:${{ steps.extract_tag.outputs.tag }}